### ISSUE TITLE
settings module is missing

### ISSUE THREAD

**Issue by sevein** [nickwilkinson/projectmatica#61]
This blocks #56.

`asites/settings.py` should be tracked by this repository. I would suggest to update the .gitignore file so the file is not ignored anymore and add it to the repo.

This is a good example on how to read configuration attributes from the string environment: https://github.com/artefactual/archivematica-storage-service/blob/stable/0.10.x/storage_service/storage_service/settings/base.py. `get_env_variable` makes the environment string to be mandatory, i.e. the application will fail during the startup process if the string is undefined.

Sometimes you may also prefer to use `os.environ` directly, e.g.: when you don't want to make the environment string mandatory. As follows:

```python
from os import environ

# Result will be None if the environment string is undefined
MY_SUPER_SECRET = environ('PROJECTMATICA_MY_SUPER_SECRET')

# Result will be "default" if the environment string is undefined
MY_OTHER_SECRET = environ('PROJECTMATICA_MY_OTHER_SECRET', 'default')
```

I'm happy to CR once you get this going. It's not something I can do for you because @nickwilkinson you're the only person with a copy of the current settings module. Just make sure you don't leave any secret behind before you commit it :)

**Comment by sevein** [comment]
@nickwilkinson, in production you probably have a file like: `/etc/systemd/system/projectmatica.service` to have systemd (the process supervisor) run Gunicorn for you. Inside that file there should be a line starting with `ExecStart=gunicorn` or similar. You can edit it to pass the environment variables you need in your settings module. There is one example here: http://docs.gunicorn.org/en/stable/settings.html#raw-env. I think that the arg `--env FOO=BAR` can be used as many times as you need, e.g.:

    $ gunicorn -b 127.0.0.1:8000 --env MY_SUPER_SECRET=1 --env MY_OTHER_SECRET=2 test:app

**Comment by nickwilkinson** [comment]
Closing this issue. I opened #64 to incorporate suggestions sevein discussed on PR #63.
